# This is a basic workflow to help you get started with Actions

name: CICDenv

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - main
     - release
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
 ENV : "null"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  determine_env:
    name: determine env
    runs-on: ubuntu-latest    
    steps: 
      - run: |
          echo "event name " $GITHUB_EVENT_NAME
          echo "event ref " $GITHUB_REF
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]] && [[ $GITHUB_REF == 'refs/heads/main' ]] ; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "dev env"
          elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
            echo "staging env"
          elif [[ $GITHUB_REF == 'refs/heads/release' ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "prod env"
          fi        
      - run: echo "environnent is " ${{ env.ENV }}
  build:
    name: build
    needs: [determine_env]
    runs-on: ubuntu-latest
    environment: 
      name: ${{ env.ENV }}
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: echo "Build"
  test:
    name: test
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: ${{ env.ENV }}
    steps:
      # Runs a set of commands using the runners shell
      - name: Run test
        run: |
          echo "Test"
 
