# This is a basic workflow to help you get started with Actions

name: curl

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - feature6
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VAULT_ADDR: https://vault-bde-1.vault-service-ccfs.fr:8200
      VAULT_TOKEN: s.BmWE4Io3hWmqTHPuJLHI7TOW 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2   
      
      - name: get token for getting approle role id
        run: |
          export VAULT_TOKEN=${{ env.VAULT_TOKEN }};
          echo "{ -policy="approle-api-roleid-get" -policy="approle-api-roleid-get" }" > payload-roleid.json
          echo "ROLE_ID_TOKEN=`curl --header \"X-Vault-Token: $VAULT_TOKEN\" --request POST --data @payload-roleid.json $VAULT_ADDR/v1/auth/token/create | jq '.auth.client_token'`" >> $GITHUB_ENV;
          echo $ROLE_ID_TOKEN;
