# This is a basic workflow to help you get started with Actions

name: python

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - main
     - release
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2    

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "true"
          path: "./requirements.txt"
          
      # Access resources using vault GCP SA key
      - name: Call Python function
        run: |
          export vault_addr="myAddress"
          export vault_ca="myCA"
          export github_pat="myGithubPat"
          my_sa_key=`python sa_key_roleset.py $vault_addr $vault_ca $github_pat`
          echo "my_sa_key" $my_sa_key
